version: '3'
services:
  web:
    build: .
    ports: 
      - 8080:8080
    volumes:
      - ./app:/app
    command: bash -c "supervisord -n"
    environment:
      SLACK_TOKEN: ${SLACK_TOKEN}
      MONGO_URI: ${MONGO_URI}
      FLASK_ENV: production
